name: Deploy PatrolD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create environment file
      run: |
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
        echo "PGUSER=${{ secrets.PGUSER }}" >> .env
        echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .env
        echo "PGHOST=${{ secrets.PGHOST }}" >> .env
        echo "PGPORT=${{ secrets.PGPORT }}" >> .env
        echo "PGDATABASE=${{ secrets.PGDATABASE }}" >> .env
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
        echo "PORT=5000" >> .env

    # PostgreSQL Client zaten kurulu olduğunu varsayıyoruz
        
    - name: Run database migrations
      run: |
        # Create schema if it doesn't exist
        PGPASSWORD=${{ secrets.PGPASSWORD }} psql -h ${{ secrets.PGHOST }} -p ${{ secrets.PGPORT }} -U ${{ secrets.PGUSER }} -d ${{ secrets.PGDATABASE }} -c "CREATE SCHEMA IF NOT EXISTS public;"
        
        # Now run the database migrations
        npm run db:push

    - name: Build application
      run: npm run build

    - name: Restart PM2 service
      run: |
        # PM2 ecosystem.config.js oluştur
        cat > ecosystem.config.cjs << EOL
module.exports = {
  apps: [{
    name: "patrold",
    script: "npm",
    args: "start",
    instances: 1,
    autorestart: true,
    watch: false,
    max_memory_restart: "500M",
    env: {
      NODE_ENV: "production",
      PORT: 5000,
      DATABASE_URL: "${{ secrets.DATABASE_URL }}",
      PGUSER: "${{ secrets.PGUSER }}",
      PGPASSWORD: "${{ secrets.PGPASSWORD }}",
      PGHOST: "${{ secrets.PGHOST }}",
      PGPORT: "${{ secrets.PGPORT }}",
      PGDATABASE: "${{ secrets.PGDATABASE }}",
      TELEGRAM_BOT_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}",
      SESSION_SECRET: "${{ secrets.SESSION_SECRET }}"
    }
  }]
};
EOL
        
        # PM2 ile uygulamayı başlat
        pm2 delete patrold || true
        pm2 start ecosystem.config.cjs
        pm2 save

    - name: Package Debian
      run: ./build_deb.sh

    - name: Deploy to web directory
      run: |
        cp patrold_1.0.0_all.deb /var/www/html/
        
    - name: Notification
      if: success()
      run: |
        echo "PatrolD deployment completed successfully!"